// src/components/timeline/TimelineElement.tsx
import React, { Component } from 'react'
import { TimelineElementData, TimelineElementPosition } from '../introduciton/Timeline/TimelineContainer'
import { TextAlignProperty, Properties } from 'csstype'

export default class TimelineElement extends Component {
  private timelineData!: TimelineElementData
  private index!: number
  private contentAlignment: any = null
  private iconAlignment: any = { fontSize: 'var(--icon-font-size)' }
  private animationDirection: string = ''

  created() {
    this.getJustifying()
  }

  private get timelineElementPosition() {
    const column: number = this.timelineData.position
    const row: number = this.index + 1
    const textAlign: TextAlignProperty = TimelineElementPosition[column].toLowerCase() as TextAlignProperty

    return {
      gridColumn: column,
      gridRow: row,
      textAlign,
    }
  }

  private getJustifying(): void {
    const alignStart: Properties = { alignSelf: 'start' }
    const alignEnd: Properties = { alignSelf: 'end' }

    if (this.timelineData.position === TimelineElementPosition.LEFT) {
      this.contentAlignment = alignStart
      this.iconAlignment = { ...this.iconAlignment, ...alignEnd }
      this.animationDirection = 'zoom-out-right'
    } else {
      this.contentAlignment = alignEnd
      this.iconAlignment = { ...this.iconAlignment, ...alignStart }
      this.animationDirection = 'zoom-out-left'
    }
  }

  render() {
    return (
      <div
        className="timeline-element"
        style={this.timelineElementPosition}
        data-aos={this.animationDirection}
        data-aos-delay="400"
        data-aos-once="true"
      >
        {/* <font-awesome-icon icon={this.timelineData.icon} className="mb-1" style={this.iconAlignment} /> */}
        <div className="timeline-element-border" style={this.contentAlignment} />
        <h2 className="timeline-content" style={this.contentAlignment}>
          {this.timelineData.header}
        </h2>
        <h3 className="timeline-content" style={this.contentAlignment}>
          {this.timelineData.subheader}
        </h3>
        <h4 className="timeline-content mb-1" style={this.contentAlignment}>
          {this.timelineData.place} | {this.timelineData.time}
        </h4>
        <p className="timeline-content" style={this.contentAlignment}>
          {this.timelineData.information}
        </p>
      </div>
    )
  }
}

// src/components/Timeline/TimelineElement.vue
<template>
  <div
    class="timeline-element"
    :style="timelineElementPosition"
    :data-aos="animationDirection"
    data-aos-delay="400"
    data-aos-once="true"
  >
    <font-awesome-icon :icon="timelineData.icon" class="mb-1" :style="iconAlignment"></font-awesome-icon>
    <div class="timeline-element-border" :style="contentAlignment"/>
    <h2 class="timeline-content" :style="contentAlignment">{{timelineData.header}}</h2>
    <h3 class="timeline-content" :style="contentAlignment">{{timelineData.subheader}}</h3>
    <h4
      class="timeline-content mb-1"
      :style="contentAlignment"
    >{{timelineData.place}} | {{timelineData.time}}</h4>
    <p class="timeline-content" :style="contentAlignment">{{timelineData.information}}</p>
  </div>
</template>
<script lang="ts">
import Vue from 'vue'
import Component from 'vue-class-component'
import { Prop } from 'vue-property-decorator'
import { Properties, TextAlignProperty, AlignSelfProperty, SelfPosition } from 'csstype'
import { TimelineElementData, TimelineElementPosition } from '@/components/Timeline/TimelineContainer.vue'

@Component
export default class TimelineElement extends Vue {
  @Prop() private timelineData!: TimelineElementData
  @Prop() private index!: number
  private contentAlignment: Properties | null = null
  private iconAlignment: Properties | null = { fontSize: 'var(--icon-font-size)' }
  private animationDirection: string = ''

  private created() {
    this.getJustifying()
  }

  private get timelineElementPosition(): Properties {
    const column: number = this.timelineData.position
    const row: number = this.index + 1
    const textAlign: TextAlignProperty = TimelineElementPosition[column].toLowerCase() as TextAlignProperty

    return {
      gridColumn: column,
      gridRow: row,
      textAlign,
    }
  }

  private getJustifying(): void {
    const alignStart: Properties = { alignSelf: 'start' }
    const alignEnd: Properties = { alignSelf: 'end' }

    if (this.timelineData.position === TimelineElementPosition.LEFT) {
      this.contentAlignment = alignStart
      this.iconAlignment = { ...this.iconAlignment, ...alignEnd }
      this.animationDirection = 'zoom-out-right'
    } else {
      this.contentAlignment = alignEnd
      this.iconAlignment = { ...this.iconAlignment, ...alignStart }
      this.animationDirection = 'zoom-out-left'
    }
  }
}
</script>
<style scoped>
.timeline-element {
  display: flex;
  flex-direction: column;
  width: 100%;

  white-space: pre-line;
}

.timeline-element-border {
  border-top: var(--primary-border);
  width: 100%;
}
</style>
